### ISSUE TITLE
Latest qor-example requires at least golang v1.8

### ISSUE THREAD

**Issue by muhammadn** [qor/qor-example#89]
I was using golang v1.7.3 prior to upgrading to 1.8 because of the error:

```
# github.com/qor/admin
../go/src/github.com/qor/admin/route.go:92: undefined: sort.SliceStable
```

After upgrading to 1.8, the error is no longer there.

**Comment by muhammadn** [comment]
Commit #90 corrects the documentation

**Comment by bodhi** [comment]
Closed by #90
